[package]
name = "algorithmz"
version = "0.9.3"
edition = "2024"
readme = "README.md"
license = "MIT OR Apache-2.0"
documentation = "https://docs.rs/algorithmz/0.9.3/algorithmz/"
authors = ["Szabó Dániel Ernő <r3ap3rpy@gmail.com>"]
description = "This is the corresponding implemenation of the python module of the same name."
repository = "https://github.com/r3ap3rpy/algorithms"
keywords = ["algorithms","data_structures","dynamic","searching","streaming"]
[dependencies]
