pub mod decode_string_tests;
pub mod count_binary_substring_tests;
pub mod contain_string_tests;
pub mod check_pangram_tests;
pub mod caesar_cipher_tests;
pub mod breaking_bad_tests;
pub mod atbash_cipher_tests;
pub mod alphabet_board_path_tests;
pub mod add_binary_tests;
