pub mod valid_parenthesis_tests;
pub mod switch_pairs_tests;
pub mod slutter_tests;
pub mod simplify_path_tests;
pub mod remove_min_tests;
pub mod ordered_stack_tests;
pub mod longest_path_tests;
pub mod is_sorted_tests;
pub mod is_consecutive_tests;
